In [4]:
import numpy as np
np.linspace(0,20,10)#short, end, numer of points requires

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [11]:
import numpy as np
np.random.randint(1,20,20)

array([ 1, 12,  2, 11, 12, 19,  6,  9,  4, 16, 13,  3,  7, 15,  8, 18, 19,
        8, 13,  6])

In [28]:
np.ones(10)*0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.ones(10)*10

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [20]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [21]:
np.ones(10)*1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [31]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [27]:
import numpy as np

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
import numpy as np
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
np.random.rand(1)

array([0.22175387])

In [10]:
np.random.randn(15)

array([ 0.8115535 , -1.02693693, -0.72568082,  0.24673353, -1.04104832,
        1.35471   ,  0.0399707 , -0.9198837 , -0.42883546, -0.2671009 ,
        0.19763514, -0.51447825, -1.61731983,  0.54605991,  0.10570107])

In [13]:
np.arange(0,100).reshape(10,10)/100

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
       [0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79],
       [0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89],
       [0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]])

In [12]:
np.linspace(0,1)#short, end, numer of points requires

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [35]:
import numpy as np
a=np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [36]:
a[2,2:5]

array([13, 14, 15])

In [37]:
a[2:5,1:5] 

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [38]:
a[1:,2:]

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [39]:
a[3:4:,-1]

array([20])

In [92]:
a[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [93]:
a[4:]

array([[21, 22, 23, 24, 25]])

In [98]:
a[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [99]:
a.sum()

325

In [100]:
a.std()

7.211102550927978

In [101]:
sum(a)

array([55, 60, 65, 70, 75])

In [106]:
a.sum(1)

array([ 15,  40,  65,  90, 115])

In [113]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [114]:
np.arange(12)*0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [115]:
np.arange(1,13).reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [56]:
import numpy as np
a=np.arange(1,15)
a                

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [55]:
np.arange(0,12).reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [3]:
import numpy as np
a=np.arange(0,12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
a.dtype

dtype('int32')

In [11]:
a.shape

(3, 4)

In [12]:
a.ndim

2

In [16]:
np.zeros(12).reshape(3,2,2)

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [12]:
np.ones(12).reshape(3,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
marks=np.random.randint(0,101,20)
marks

array([31,  5,  8, 10, 48,  9, 80, 32, 81, 46, 62, 62, 49, 61, 45, 94, 10,
       89, 27, 37])

In [18]:
ase=np.sort(marks)
ase

array([ 1,  9,  9, 18, 32, 38, 43, 54, 55, 60, 62, 66, 67, 72, 73, 74, 80,
       80, 82, 85])

In [19]:
np.flip(ase)

array([85, 82, 80, 80, 74, 73, 72, 67, 66, 62, 60, 55, 54, 43, 38, 32, 18,
        9,  9,  1])

In [26]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [66]:
np.arange(1,26)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [28]:
np.eye(5).flatten()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [67]:
np.eye(5).reshape(25)

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [30]:
np.eye(5).ravel()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [46]:
mat=np.arange(1,10).reshape(3,3)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
np.append(mat,[[9,10,11]],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 9, 10, 11]])

In [ ]:
vstack,hstack,vsplit,hsplit

In [45]:
np.split(mat,3,axis=1)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [47]:
np.hsplit(mat,3)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [48]:
np.vsplit(mat,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [48]:
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [51]:
import numpy as np
g=np.eye(4)
g+4

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [65]:
a=np.random.uniform(1,9,10)
a

array([8.35128868, 4.81471967, 2.61462599, 2.41943023, 5.1145937 ,
       6.9809698 , 1.57795903, 3.87124775, 2.82289263, 5.41340049])

In [66]:
np.ceil(a)

array([9., 5., 3., 3., 6., 7., 2., 4., 3., 6.])

In [67]:
np.floor(a)

array([8., 4., 2., 2., 5., 6., 1., 3., 2., 5.])

In [69]:
np.round(a,decimals=2)

array([8.35, 4.81, 2.61, 2.42, 5.11, 6.98, 1.58, 3.87, 2.82, 5.41])

In [73]:
a=np.arange(0,25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [74]:
np.min(a)

0

In [75]:
np.max(a)

24

In [76]:
np.var(a)

52.0

In [77]:
np.std(a)

7.211102550927978

In [65]:
j=np.zeros(10)
j[6]=200
j                                      

array([  0.,   0.,   0.,   0.,   0.,   0., 200.,   0.,   0.,   0.])

In [78]:
mv=np.arange(100,151)
mv

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [79]:
np.flip(mv)

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [80]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [110]:
a=[1,0,2,0,0,4,0,8]
a

[1, 0, 2, 0, 0, 4, 0, 8]

In [98]:
a=np.ones((10,10))
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [107]:
a[1:9,1:9]=0

In [108]:
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [64]:
import numpy as np
o=np.ones((8,8))
o[1::3,::3]=2
o

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 1., 1., 2., 1., 1., 2., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 1., 1., 2., 1., 1., 2., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 1., 1., 2., 1., 1., 2., 1.]])

In [ ]:
#Create a 3x3 matrix with random integer values. Perform matrix addition, multilication and subtraction.

In [1]:
import numpy as np 
o = np.random.randint(1,10,(3,3))
p= np.random.randint(1,10,(3,3))

In [ ]:
sum(o,p)

In [ ]:
o-p

In [ ]:
np.dot(o,p)

In [18]:
g=np.eye(4)
g+4

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])